# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "regional-account-app"
client_id = "d3c1b0227731590fed32495c420f8182"
application_url = "https://fe-cornell-range-transition.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fe-cornell-range-transition.trycloudflare.com/auth/callback",
  "https://fe-cornell-range-transition.trycloudflare.com/auth/shopify/callback",
  "https://fe-cornell-range-transition.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "joodie-store.myshopify.com"
